include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = BatteryIslandPrefs
BatteryIslandPrefs_FILES = BatteryIslandPrefsRootListController.m
BatteryIslandPrefs_INSTALL_PATH = /Library/PreferenceBundles
BatteryIslandPrefs_FRAMEWORKS = UIKit
BatteryIslandPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
